# Generated by Django 2.1.1 on 2018-10-03 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_commentslog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='client',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='info_client',
        ),
    ]
